name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows (MSVC)
            os: windows-latest
          - name: Ubuntu (GCC)
            os: ubuntu-latest
          - name: MacOS (AppleClang)
            os: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: jiro4989/setup-nim-action@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Test
      if: matrix.os == 'windows-latest'
      run: .\build\src\example.exe
    
    - name: Test
      if: matrix.os != 'windows-latest'
      run: ./build/src/example
